# Generated by Django 3.1.6 on 2021-02-15 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20210215_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='status',
        ),
    ]
